### ISSUE TITLE
Download Scanlations 

### ISSUE THREAD

**Issue by vic1707** [raehik/webtoon-dl#1]
Hi, thanks for this amazing soft !
Is there any way to download scanlations ?

**Comment by raehik** [comment]
If I understand you correctly (translations provided as overlaid subtitles?), then I don't support it here, but it might be possible - provided this program still works. It's been 3 years, so LINE Webtoon might have changed their internal API.

I'd be happy to give it a look. Could you please provide me an example page of a comic with scanlations?

**Comment by vic1707** [comment]
Ok I understand, it would be amazing if you can do it.
I was looking for "The gamer" in french ^^

**Comment by raehik** [comment]
On first glance, it appears translations are handled in Javascript. My script parses the DOM for images and downloads them - that part still works, but it always downloads the English comic.

**Comment by raehik** [comment]
Some tinkering in the dev console shows that they have some JS that replaces images with translated ones at translate-phinf.pstatic.net . e.g. https://translate-phinf.pstatic.net/20190318_149/1552886110867TL6gm_JPEG/9DgIXR6Xt3weomoLive8.jpg

Life's moved on in 3 years, I don't have the ability to spend a few days figuring this out. I'd be happy to help you solve it though. One solution may be to use a library that imitates a browser with JavaScript. That way you could tell it to select the French translation, and then download the images that it replaces in the DOM.

**Comment by raehik** [comment]
@vic1707 : I'm closing this issue because I don't believe I'm able to help further here. Good luck, and please let me know if you're interested in finding a solution yourself, I'd be happy to assist!

**Comment by vic1707** [comment]
Yes I'll try but I don't have any notion to do this king of job so it'll be difficult.
